---
- hosts: all
  tasks:
    - name: ensure yum-utils is at the latest version
      yum: pkg=yum-utils state=latest
      become: yes
    - name: add docker repo
      command: /usr/bin/yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      become: yes
    - name: ensure docker is at the latest version
      yum:
        disable_gpg_check: yes
        pkg: docker-ce
        state: latest
      notify:
      - restart docker
      become: yes
    - name: ensure docker-engine is running
      service: name=docker state=started
      become: yes
  handlers:
    - name: restart docker
      service: name=docker state=restarted
      become: yes
